package com.bawei.dianshang2019122.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.dianshang2019122.bean.EntiyBean;

import com.bawei.dianshang2019122.db.EntiyBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig entiyBeanDaoConfig;

    private final EntiyBeanDao entiyBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        entiyBeanDaoConfig = daoConfigMap.get(EntiyBeanDao.class).clone();
        entiyBeanDaoConfig.initIdentityScope(type);

        entiyBeanDao = new EntiyBeanDao(entiyBeanDaoConfig, this);

        registerDao(EntiyBean.class, entiyBeanDao);
    }
    
    public void clear() {
        entiyBeanDaoConfig.clearIdentityScope();
    }

    public EntiyBeanDao getEntiyBeanDao() {
        return entiyBeanDao;
    }

}
